### ISSUE TITLE
Use id/password with PhpSysInfo on Nginx?

### ISSUE THREAD

**Issue by inrepublica** [phpsysinfo/psiandroid#6]
Is it possible to use the id/password access when phpsysinfo is hosted on Nginx? https://github.com/YunoHost-Apps/phpsysinfo_ynh/issues/8

**Comment by namiltd** [comment]
The question is for PhpSysInfo and not for PSIAndroid. Ask them please at https://github.com/phpsysinfo/phpsysinfo/issues

**Comment by inrepublica** [comment]
Sorry, but the question is for this App. If I use id/password access for phpsysinfo on Nginx, can the application connect?

**Comment by namiltd** [comment]
In psiandroid host definition you can specify Username and Password.
