### ISSUE TITLE
Feature Request: Include "Current Action" info for Raids

### ISSUE THREAD

**Issue by CountMurphy** [phpsysinfo/psiandroid#7]
The webapp for phpsysinfo contains additional information on Raid statuses, as shown below: ![link](https://i.imgur.com/cfN8HUA.png)

It would be incredibly useful to reflect this same status information for the check action in android application.

**Comment by namiltd** [comment]
Look at https://www.aumnia.com/blog/google-improves-webapp-support-latest-mobile-chrome-release
Try reading this information without PSIAndoid app.

**Comment by namiltd** [comment]
Closed due to inactivity
